Added automated testing and hamburger menu rebuilding bug
Open-Acidification/TankControllerManager pull request #89
Opened 2023-01-24 23:42 UTC by Suocesky

2023-01-24 23:52 UTC, jgfoster requested changes

2023-01-24 23:52 UTC, jgfoster commented on lib/components/app_drawer.dart
> +    print("Build app drawer");
Please remove debugging code.

2023-01-24 23:52 UTC, jgfoster commented on lib/components/app_drawer.dart
> +          Align (
This should be moved to the next PR since it starts on the delete feature.

2023-01-24 23:52 UTC, jgfoster commented on lib/model/app_data.dart
> +  void removeTank(tank) {
Move to next PR.

2023-01-25 00:06 UTC, jgfoster approved these changes

2023-01-25 03:21 UTC, prestoncarman commented
LGTM

2023-01-25 03:22 UTC, merged